### PR TITLE
Openmpi tm true

### PR DESCRIPTION
**Pull request by fpruvost**
turn on (True) the variant 'thread_multiple' by default because we have several codes that need it

### CODE REVIEW

**Comment by fpruvost** [comment]
@emmanuelagullo @ramet 

- is it correct that several programs in the stack require to have mpi with "thread multiple" support?
- can the concerned programs run without this support?

**Comment by ramet** [comment]
PaStiX can take advantage of MPI with "thread multiple" support.
But a "thread funneled" option is available if MPI is not install with this support.

**Comment by emmanuelagullo** [comment]
I think the only solver in the Maphys stack for which it is important to have this level of control is Pastix.
@gmarait @matthieukuhn Do you confirm?

**Comment by fpruvost** [comment]
If I understand well, it is not mandatory to have it.

It is still interesting to have it for a specific stack, and we can use ^openmpi+thread_multiple so that it is not necessarily a good thing to make this variant `True` by default

**Comment by emmanuelagullo** [comment]
Not so sure. I think it is critical for the performance of Pastix. @ramet you confirm?

**Comment by ramet** [comment]
For the "old" version of PaStiX, the "thread multiple" implementation is quite critical for performance. But in the new version 6.0 we will do not depend on this requirement.

**Comment by fpruvost** [comment]
Thanks for your answers.

I would like to avoid useless noise so I **would like to abandon this merge request** if you're ok.

I heard that this feature is not trustworthy so that I prefer let this variant `False` by default

**Comment by emmanuelagullo** [comment]
@fpruvost Fine with me!

**Pull request closed without merging**
